title: "WEEK Radio Schedule"
description: "Циклический сайт для 24 часов вещания"
baseurl: ""  # Если сайт будет на поддомене, укажите базовый URL здесь
url: "http://127.0.0.1:4000"  # Локальный URL для тестирования

# Подключение папок с макетами, стилями и инклюдами
include:
  - "_layouts"
  - "assets"

# Локальная конфигурация
timezone: "Europe/Moscow"
